substitutions:
  mqtt_prefix: bus/devices/traffic-light

esphome:
  name: traffic-light
  comment: Mini red-green traffic light
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: esp-idf

ota:
  safe_mode: true
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  fast_connect: true

logger:

# api:

switch:
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_ON
    pin:
      number: 23
      inverted: true
    name: "Red lamp"
    id: red_lamp

  - platform: gpio
    restore_mode: RESTORE_DEFAULT_ON
    pin: 
      number: 21
      inverted: true
    name: "Green lamp"
    id: green_lamp

mqtt:
  broker: !secret mqtt_broker
  certificate_authority: !secret mqtt_ca
  discovery: false
  password: !secret mqtt_password
  port: !secret mqtt_port
  topic_prefix: ${mqtt_prefix}
  username: !secret mqtt_username
  on_message:
    - topic: ${mqtt_prefix}/red
      payload: 'on'
      then:
        - switch.turn_on: red_lamp
    - topic: ${mqtt_prefix}/red
      payload: 'off'
      then:
        - switch.turn_off: red_lamp
    - topic: ${mqtt_prefix}/green
      payload: 'on'
      then:
        - switch.turn_on: green_lamp
    - topic: ${mqtt_prefix}/green
      payload: 'off'
      then:
        - switch.turn_off: green_lamp
