substitutions:
  mqtt_prefix: bus/devices/lessar-ac

esphome:
  name: lessar-ac
  comment: Lessar LS-HE18KCE2 air conditioner

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: /Users/xanmilanto/git/esphome-fork/esphome/components
    components: [midea]

ota:
  - platform: esphome
    password: !secret api_password

api:
  encryption: 
    key: !secret encryption_key
  reboot_timeout: 0s

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  fast_connect: false

  min_auth_mode: WPA2
  power_save_mode: NONE
  reboot_timeout: 2min

logger:
  baud_rate: 0

mqtt:
  broker: !secret mqtt_broker
  certificate_authority: !secret mqtt_ca
  discovery: false
  password: !secret mqtt_password
  port: !secret mqtt_port
  topic_prefix: ${mqtt_prefix}
  username: !secret mqtt_username
  on_message:
    - topic: ${mqtt_prefix}/power/set
      payload: "on"
      then:
        - midea_ac.power_on:
    - topic: ${mqtt_prefix}/power/set
      payload: "off"
      then:
        - midea_ac.power_off:
    - topic: ${mqtt_prefix}/power/set
      payload: "toggle"
      then:
        - midea_ac.power_toggle:
    - topic: ${mqtt_prefix}/display/set
      payload: "toggle"
      then:
        - midea_ac.display_toggle:
    - topic: ${mqtt_prefix}/beeper/set
      payload: "on"
      then:
        - midea_ac.beeper_on:
    - topic: ${mqtt_prefix}/beeper/set
      payload: "off"
      then:
        - midea_ac.beeper_off:
    - topic: ${mqtt_prefix}/swing_step/set
      then:
        - midea_ac.swing_step:
    - topic: ${mqtt_prefix}/follow_me/set
      then:
        - midea_ac.follow_me:
            temperature: !lambda "return atof(x.c_str());"
            beeper: false

uart:
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 9600

climate:
  - platform: midea
    id: ac
    name: lessar_ac
    period: 3s
    timeout: 2s
    num_attempts: 1
    autoconf: false
    beeper: false
    mode_command_topic: ${mqtt_prefix}/climate/mode/set
    target_temperature_command_topic: ${mqtt_prefix}/climate/temperature/set
    swing_mode_command_topic: ${mqtt_prefix}/climate/swing_mode/set
    fan_mode_command_topic: ${mqtt_prefix}/climate/fan_mode/set
    preset_command_topic: ${mqtt_prefix}/climate/preset/set
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:
      - FAN_ONLY
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    supported_presets:
      - ECO
      - BOOST
      - SLEEP
    custom_presets:
      - FREEZE_PROTECTION
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH
    outdoor_temperature:
      name: lessar_outdoor_temp
    power_usage:
      name: lessar_power
    humidity_setpoint:
      name: lessar_humidity
